import { type Module, inject } from 'langium';
import {
    createDefaultModule,
    createDefaultSharedModule,
    type DefaultSharedModuleContext,
    type LangiumServices,
    type LangiumSharedServices,
    type PartialLangiumServices,
} from 'langium/lsp';
import { AlloyGeneratedModule, AlloyGeneratedSharedModule } from './generated/module.js';
import { AlloyValidator, registerValidationChecks } from './alloy-validator.js';
import { AlloyCompletionProvider } from './alloy-completion-provider.js';
import { AlloyScopeProvider } from './alloy-scope-provider.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type AlloyAddedServices = {
    validation: {
        AlloyValidator: AlloyValidator;
    };
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type AlloyServices = LangiumServices & AlloyAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const AlloyModule: Module<AlloyServices, PartialLangiumServices & AlloyAddedServices> = {
    validation: {
        AlloyValidator: () => new AlloyValidator(),
    },
    references: {
        ScopeProvider: (services) => new AlloyScopeProvider(services),
    },
    lsp: {
        CompletionProvider: (services) => new AlloyCompletionProvider(services),
    },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createAlloyServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices;
    Alloy: AlloyServices;
} {
    const shared = inject(createDefaultSharedModule(context), AlloyGeneratedSharedModule);
    const Alloy = inject(createDefaultModule({ shared }), AlloyGeneratedModule, AlloyModule);
    shared.ServiceRegistry.register(Alloy);
    registerValidationChecks(Alloy);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Alloy };
}
